### ISSUE TITLE
Issue with installing library in MacOSx

### ISSUE THREAD

**Issue by parunach** [BankEx/solidity-float-point-calculation#1]
I tried installing in my MBP

`npm install
`

I get the error

> module.js:538
>     throw err;
>     ^
> 
> Error: Cannot find module '../lib/utils/unsupported.js'
>     at Function.Module._resolveFilename (module.js:536:15)
>     at Function.Module._load (module.js:466:25)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
>     at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)

Any suggestions?

**Comment by shamatar** [comment]
I've updated package.json to include matching solidity compiler version, please check the last commited version.

Sincerley, Alexander

**Comment by skywinder** [comment]
0ec265cd4634f09deb5a844443bbacd923f1fddc should fix this issue. Please, kindly check.
